### ISSUE TITLE
Error with readonly_fields = ('users',)

### ISSUE THREAD

**Issue by SimKennedy** [Microdisseny/django-groupadmin-users#1]
Hi,

Thanks for the useful little app, I've just had a couple of issues I thought I'd mention

I tried using your pypi version and got this error.
```
ERRORS:
<class 'tenders.admin.GroupAdmin'>: (admin.E035) The value of 'readonly_fields[0]' is not a callable, an attribute of 'GroupAdmin', or an attribute of 'auth.Group'.
```
Commenting out this line worked, but then I realised the Users were not being populated.

I found the source of the code [on stack overflow](https://stackoverflow.com/questions/39485067/django-add-user-to-group-via-django-admin) and tried that directly in my app instead and it worked perfectly for me, including the 'users' initialising. I'd rather use a PyPi version for cleaner code and version checks in case we upgrade python/django though.

I'm guessing there may be version issues here?

I'm using Python 3.6.3 and Django 1.9.4.

Since the original code seems to be good for this configuration, could multiple versions be hosted on PyPi for ease of install? I sadly am not experienced with packaging else I would have a go at it myself.

I realise this is not that important since the code is easy enough to use, but thought I would report it in case it's simple to do

Cheers

Sim

**Comment by manelclos** [comment]
Hi @SimKennedy,

This was caused by an improper upload. Some testing code for the readonly-admin PR for Django 2.0 was in the upload. Sorry for that. I've uploaded version 0.3.3 to fix this. Please let me know if it works for you. You can check that the code that is failing has never been there (commited): https://github.com/Microdisseny/django-groupadmin-users/blob/master/groupadmin_users/admin.py

As the code is very simple, there is 100% coverage. I've improved the travis configuration to include django-2.0. Your combination though is not supported by Django, but should work anyway, https://docs.djangoproject.com/en/2.0/releases/1.9/

The reason we had for creating this package was in fact making this code easier to use and maintain.
