### ISSUE TITLE
Possibility to show Username instead of Id

### ISSUE THREAD

**Issue by lalvarezt** [Microdisseny/django-groupadmin-users#10]
Is it possible to show the username (or another field) instead of the id?

**Comment by manelclos** [comment]
Hi @lalvarezt, not sure if I understand your question. If you look at the screenshot, it is already showing the username. That is because Django's `User` model uses the `username` in the `__str__` method.

Maybe you have customised the `User` model and implemented a different `__str__` method?

We could have this configurable using `label_from_instance` option of https://docs.djangoproject.com/en/dev/ref/forms/fields/#modelmultiplechoicefield

PRs welcome anytime :)

**Comment by lalvarezt** [comment]
Hi @manelclos  thanks for the feedback
Manage to solve by overriding `label_from_instance` in the `GroupAdminForm` class definition

`users.label_from_instance = lambda x: x.name`
